### PR TITLE
[semver:minor] - Remove --fail-on-pending

### PR DESCRIPTION
**Pull request by JackyLiHelix**
This broke some repos because it had pending specs. Removing it for now.

### CODE REVIEW

**Review by brian-helix — APPROVED** [review]

**Review by nick-armstrong-helix — APPROVED** [review]
That's a bummer...

**Comment by JackyLiHelix** [comment]
> That's a bummer...

It is. But I don't want to tell everyone start using `Skip` instead 😓

**Comment by brian-helix** [comment]
It is mostly older tests from older repos that presumably broke at some point that are marked as "XDescribe", likely because it was deemed to be quicker to mark the tests as pending than to fix them: https://github.com/search?q=org%3Amyhelix+XDescribe&type=code

**Comment by JackyLiHelix** [comment]
> It is mostly older tests from older repos that presumably broke at some point that are marked as "XDescribe", likely because it was deemed to be quicker to mark the tests as pending than to fix them: https://github.com/search?q=org%3Amyhelix+XDescribe&type=code

Proper way is to use `Skip('some message') inside the Describe/It. Pending is usually used for WIP, but we don't need to force this rule of "never commit WIP tests"

I think it's fine to remove this argument.

I might add a `ginkgo_additional_params` optional param to allow teams to add these non-standard bits.

**Pull request merged**
