### PR TITLE
replace devops with engineering team as devops team is no more

### PR DESCRIPTION
**Pull request by ZuhaibSiddiqueHelix**
Change code owner to reflect that all of @myhelix/engineering is the owner of this project

### CODE REVIEW

**Comment by helixliam** [comment]
Hey @ZuhaibSiddiqueHelix is it possible to designate an individual code owner, someone who has a particularly good knowledge of the service, in accordance with **Option 1** [here](https://myhelix.atlassian.net/wiki/spaces/SEC/pages/2818834445/Code+ownership+in+GitHub)? Having the only code owner be `@myhelix/engineering` is counter to the goal of being able to identify a “go-to” contact for urgent issues, and minimize toil when a code or infrastructure change needs to be applied to several different projects.

**Comment by ZuhaibSiddiqueHelix** [comment]
Sounds fine, @corrjo according to most commits you would be the winner

**Comment by corrjo** [comment]
Haha I'd be fine with taking it but it has been awhile since I made those. @ZuhaibSiddiqueHelix you're the winner by most recent commits :P  We could also leave @yeaji-helix as the codeowner. 

In the spirit of the guild I've actually been trying to diversify devops-team codeownership a bit. I've been thinking about how best to split up ownership on some of shared repos, so @ZuhaibSiddiqueHelix If you _want_ to be codeowner here it'd help that initiative. 

Another option is to reach out to the cloud team, but I think we wouldn't necessarily need the cloud team to own orb code, even if they own the circleci service. 🤔

**Comment by ZuhaibSiddiqueHelix** [comment]
fine, i added myself as code owners

**Review by corrjo — APPROVED** [review]
Thanks @ZuhaibSiddiqueHelix! We can definitely always change it too.

**Pull request merged**
