### PR TITLE
[semver:minor] Add golang versions 20 and 21 to enums

### PR DESCRIPTION
**Pull request by SoniaSeguraHelix**

### CODE REVIEW

**Review by tomthomas-helix — APPROVED** [review]
lgtm, thanks for the update!

**Review by emreathelix — APPROVED** [review]

**Review by JackyLiHelix — APPROVED** [review]

**Comment by JackyLiHelix** [comment]
Thank you for adding support to latest golang versions!

**Review by tomthomas-helix — COMMENTED** [review]
actually, might need to add support here as well: https://github.com/myhelix/circleci-runner/blob/main/lib/circleci-runner-stack.ts#L23

**Comment by SoniaSeguraHelix** [comment]
Hi! there's a [PR](https://github.com/myhelix/circleci-runner/pull/82) for the change in circleci-runner

**Pull request merged**
